name: Trigger auto deployment for liana-sandbox

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/liana-sandbox-AutoDeployTrigger-07c68a0c-94a1-4dc5-a928-10ed95ad07d1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.LIANASANDBOX_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LIANASANDBOX_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LIANASANDBOX_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.LIANASANDBOX_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LIANASANDBOX_REGISTRY_PASSWORD }}
          containerAppName: liana-sandbox
          resourceGroup: ladaza
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


